### ISSUE TITLE
False positive for addOnloadHook

### ISSUE THREAD

**Issue by Krinkle** [he7d3r/mw-gadget-jsUpdater#1]
<img width="295" alt="screen shot 2016-06-15 at 02 56 37" src="https://cloud.githubusercontent.com/assets/156867/16065416/db2d4150-32aa-11e6-86ca-e413c8f5b359.png">

Would be nice to exclude these from the regex match.

**Comment by he7d3r** [comment]
@Krinkle: I think ~~https://github.com/he7d3r/mw-gadget-jsUpdater/commit/e9944a69e56398b0e848499e59757149030eb09f~~ https://github.com/he7d3r/mw-gadget-jsUpdater/commit/5ab3ed33f4ca438596337458806092d10be9fd7f fixes it.

PS: how did you generate this diff/screenshot?

**Comment by Krinkle** [comment]
@he7d3r It's a little script I'm working on for making it easier to do global interface edits.
See https://gist.github.com/Krinkle/8e1e0e41baaae63f9839d86d918d512c.
